# Generated by Django 5.0.4 on 2024-04-16 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babe',
            name='age',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payno', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='Ugx', max_length=3, null=True)),
                ('c_pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kash.categorystay')),
            ],
        ),
    ]
