# Generated by Django 5.0.4 on 2024-04-19 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0002_alter_babe_age_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babe',
            old_name='timeIn',
            new_name='time_in',
        ),
        migrations.RenameField(
            model_name='babe',
            old_name='timeOut',
            new_name='time_out',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payno',
            new_name='pay_no',
        ),
        migrations.RemoveField(
            model_name='babe',
            name='location',
        ),
        migrations.AddField(
            model_name='payment',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kash.babe'),
        ),
        migrations.AlterField(
            model_name='babe',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='babe',
            name='sponsor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categorystay',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, default='Ugx', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='babe',
            name='Location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
