# Generated by Django 5.0.4 on 2024-04-19 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kash', '0003_rename_timein_babe_time_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babe',
            old_name='Location',
            new_name='location',
        ),
    ]
